config/routes.rb
Rails.application.routes.draw do
  resources :organization_tags

  resources :person_tags

  resources :post_tags

  resources :tags

  resources :posts

  resources :people

  resources :organizations

  devise_for :users

  get 'user_root' => 'users#details', as: :user_root

  root 'posts#index'

end

app/models/organization_tag.rb
class OrganizationTag < ActiveRecord::Base
  belongs_to :organization
  belongs_to :tag
end

app/controllers/organization_tags_controller.rb
class OrganizationTagsController < ApplicationController
  before_action :set_organization_tag, only: [:show, :edit, :update, :destroy]

  # GET /organization_tags
  # GET /organization_tags.json
  def index
    @organization_tags = OrganizationTag.all
  end

  # GET /organization_tags/1
  # GET /organization_tags/1.json
  def show
  end

  # GET /organization_tags/new
  def new
    @organization_tag = OrganizationTag.new
  end

  # GET /organization_tags/1/edit
  def edit
  end

  # POST /organization_tags
  # POST /organization_tags.json
  def create
    @organization_tag = OrganizationTag.new(organization_tag_params)

    respond_to do |format|
      if @organization_tag.save
        format.html { redirect_to @organization_tag, notice: 'Organization tag was successfully created.' }
        format.json { render :show, status: :created, location: @organization_tag }
      else
        format.html { render :new }
        format.json { render json: @organization_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_tags/1
  # PATCH/PUT /organization_tags/1.json
  def update
    respond_to do |format|
      if @organization_tag.update(organization_tag_params)
        format.html { redirect_to @organization_tag, notice: 'Organization tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_tag }
      else
        format.html { render :edit }
        format.json { render json: @organization_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_tags/1
  # DELETE /organization_tags/1.json
  def destroy
    @organization_tag.destroy
    respond_to do |format|
      format.html { redirect_to organization_tags_url, notice: 'Organization tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_tag
      @organization_tag = OrganizationTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_tag_params
      params.require(:organization_tag).permit(:organization_id, :tag_id)
    end
end

app/helpers/organization_tags_helper.rb
module OrganizationTagsHelper
end

app/views/organization_tags/_form.html.erb
<%= form_for(@organization_tag) do |f| %>
  <% if @organization_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization_tag.errors.count, "error") %> prohibited this organization_tag from being saved:</h2>

      <ul>
      <% @organization_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organization_tags/edit.html.erb
<h1>Editing Organization Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization_tag %> |
<%= link_to 'Back', organization_tags_path %>

app/views/organization_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organization Tags</h1>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_tags.each do |organization_tag| %>
      <tr>
        <td><%= organization_tag.organization_id %></td>
        <td><%= organization_tag.tag_id %></td>
        <td><%= link_to 'Show', organization_tag %></td>
        <td><%= link_to 'Edit', edit_organization_tag_path(organization_tag) %></td>
        <td><%= link_to 'Destroy', organization_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization tag', new_organization_tag_path %>

app/views/organization_tags/new.html.erb
<h1>New Organization Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', organization_tags_path %>

app/views/organization_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @organization_tag.organization_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @organization_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_organization_tag_path(@organization_tag) %> |
<%= link_to 'Back', organization_tags_path %>