config/routes.rb
Rails.application.routes.draw do
  resources :organization_tags

  resources :person_tags

  resources :post_tags

  resources :tags

  resources :posts

  resources :people

  resources :organizations

  devise_for :users

  get 'user_root' => 'users#details', as: :user_root

  root 'posts#index'

end

app/views/layouts/_carousel.html.erb
<div class='carousel-wrapper'>
  <div id="carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      <li data-target="#carousel-example-generic" data-slide-to="4"></li>
      <li data-target="#carousel-example-generic" data-slide-to="5"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="images/anna_carousel.jpg" alt="...">
      </div>
      <div class="item">
        <img src="images/ben_carousel.jpg" alt="...">
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <img src="images/carousel3.jpg" alt="...">
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <img src="images/carousel_V4.jpg" alt="...">
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <img src="images/repack_carousel.jpg" alt="...">
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <img src="images/joni_carousel.jpg" alt="...">
        <div class="carousel-caption">
        </div>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Events', posts_path %></li>
<li><%= link_to 'Organizations', organizations_path %></li>
<li><%= link_to 'People', people_path %></li>

app/views/layouts/_navigation_links_right.html.erb
<% if current_user %>
  <li><%= link_to 'My profile', person_path(current_user.person) %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Sign up',  new_user_registration_path %></li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <title>Employouth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div id="navbar-header">
      <button class='navbar-toggle' data-target='.navbar-collapse' data-toggle='collapse' type='button'>
      <span class='sr-only'>Toggle navigation</span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      </button>
      <a class='navbar-brand' href="<%= root_path %>">
        Emplo<strong>YOUTH</strong>
      </a>
      </div>
      <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </nav>
  <%= render 'layouts/carousel' if params[:controller] == 'posts' && params[:action] == 'index' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>